### ISSUE TITLE
Can coverallsget the locations of coverdata from coverspec file?

### ISSUE THREAD

**Issue by linearregression** [markusn/coveralls-erl#13]
Hi,

The coverspec file already indicates the location of exported coverdata 
We can read from the spec file if present. There is a sister project but no a rebar plugin (see link end of message)
Also each run of ct creates its own directory for logs and coverdata, can you enhance the tool to support that?
Ref:
* http://www.erlang.org/doc/apps/common_test/cover_chapter.html
* https://github.com/nifoc/ecoveralls

**Comment by markusn** [comment]
The cover spec cannot be used as rebar uses a specific folder for cover for eunit. My understanding is that you want to merge all available coverage data and then sending it to coveralls, this can be done by adding a `cover.spec` file with:

```erlang 
{import, ".eunit/cover.coverdata"}.
{export, "logs/all.coverdata"}.
```
And then adding the following lines to your `rebar.config`:

```erlang
{coveralls_coverdata, "logs/all.coverdata"},
{plugins , [{coveralls, {git, "https://github.com/markusn/coveralls-erl", "master"}}]}.
{cover_enabled  , true}.
{coveralls_service_name , "travis-ci"}.
{cover_export_enabled , true}.
{do_coveralls_after_ct, false},
{do_coveralls_after_eunit, false},

And then use `rebar skip_deps=true eunit ct send-coveralls`. This way eunit will run first, then ct which will use the `cover.spec` and export the merged result to `logs/all.coverdata` which the send-coveralls task will deliver to coveralls. do_coveralls_after_ct and do_coveralls_after_eunit will ensure that sending coveralls data does not happen before send-coveralls is used.
