### ISSUE TITLE
Fails on rebar3 "need to specify coveralls_* and cover_export_enabled in rebar.config" but already set i rebar.config

### ISSUE THREAD

**Issue by linearregression** [markusn/coveralls-erl#14]
rebar.config:
{require_min_otp_vsn, "17"}.
{plugins , [{coveralls, {git, "https://github.com/markusn/coveralls-erl", "master"}}]}.
{cover_enabled, true}.
{cover_print_enabled, true}.
{cover_export_enabled, true}.
{cover_opts, [verbose]}.
{coveralls_coverdata, "log/all.coverdata"}.
{coveralls_service_name , "travis-ci"}.
{ct_opts, [{logdir, "log/ct"},
    {dir, "./test/"},
    {include, ["include"]},
    {suites, "test", all},
    {cover,"test/replication.coverspec"},
    {suite, [
        replication_SUITE
    ]}
]}.

replication.coverspec:
{import, ".eunit/cover.coverdata"}.
{export, "logs/all.coverdata"}.
{level, details}. 

env DEBUG=1 rebar3 coverall send
===> Evaluating config script "rebar.config.script"
===> Evaluating config script "/opt/test/ReplicationEngine/_build/default/plugins/coveralls/rebar.config.script"
===> Evaluating config script "/opt/test/ReplicationEngine/_build/default/plugins/coveralls/rebar.config.script"
===> Expanded command sequence to be run: []
===> Expanded command sequence to be run: [{default,app_discovery},
                                                  {coveralls,send}]
===> Evaluating config script "/opt/test/ReplicationEngine/rebar.config.script"
===> Running coveralls...
===> need to specify coveralls_* and cover_export_enabled in rebar.config
make: *** [coverage-report] Error 1

**Comment by markusn** [comment]
It looks a bit strange, it should be rebar3 coveralls send (not coverall). But the real problem seems to be that coveralls_service_job_id is not set. Try adding a rebar.config.script with the following content:

```erlang
case os:getenv("TRAVIS") of
  "true" ->
    JobId   = os:getenv("TRAVIS_JOB_ID"),
    lists:keystore(coveralls_service_job_id, 1, CONFIG, {coveralls_service_job_id, JobId});
  _ ->
    CONFIG
end.
```

**Comment by linearregression** [comment]
https://github.com/markusn/coveralls-erl/blob/master/rebar.config.script
this is the rebar.config.script I used when the error happens

**Comment by markusn** [comment]
Provide me with a link to the Travis job that is failing and I will debug it.

**Comment by linearregression** [comment]
I fixed some of the issues on the config. 
But as you see in the task, it fails on all except erlang 17.

https://travis-ci.org/linearregression/ReplicationEngine/builds/89278297

**Comment by markusn** [comment]
Strange that it works on R17 but nothing else! I will have look later this week and try to figure it out.

**Comment by linearregression** [comment]
yes it is strange, especially if you put the coverage submission portion under after-success: the error won't show up. Since only one is green and it submits the number,it is hard to discover that when you just look at the code coverage icon.

**Comment by linearregression** [comment]
Added a script to copy over coverdata before running coveralls. 
It fixes some variants but it looks like there are quite some instability on the otp library side:

https://travis-ci.org/linearregression/ReplicationEngine/builds/89532349

**Comment by markusn** [comment]
I've had a look at this. (see https://github.com/markusn/ReplicationEngine/tree/coveralls-working - works on all but 17.3). The problem is, as you state, that CT behaves differently on different versions of Erlang/OTP. In general it seems better to put the coverspec file in the folder which the coverdata path is relative to. Howeve sometimes this is not sufficient and CT does respect the path given in the spec file. A workaround would be to set coveralls_coverdata from a script (rebar.config.script) if a version of Erlang/OTP is used that does not respect the spec file (17.3 from my experiments). In either case this is not a bug in coveralls-erl and I hope the above workaround(s) are sufficient.

**Comment by linearregression** [comment]
Thanks. I am honesty a bit disappointed when I see it is the ct side and was confirmed by you. 
Suspicion arised when I compared to the other project. 
Do you think it worth documenting that in README.md? Most peoplewillput that under after-success: i travis.yml. If any of the sub-build tasks is able to send the result, it will show up on coverall.

**Comment by markusn** [comment]
Yes, I will add it to the README, thanks!
