### ISSUE TITLE
Bad appdir imports with non-test rebar3 profile

### ISSUE THREAD

**Issue by Motiejus** [markusn/coveralls-erl#16]
When coveralls is used in a non-`test` rebar3 profile, cover_paths is trying to add incorrect application directories. You can reproduce it by making coveralls to run in a rebar3 profile. Alternatively, you can use my project (requires `python-dev`, `virtualenv` in `$PATH`, and Erlang 17.0+):

1. Clone https://github.com/Motiejus/tchannel-erlang/tree/74ed3a12bdcc69cf08016dad71007dc2e5658080
2. `make setup proper test cover coveralls`
3. Observe the stack trace. With the diff to coveralls below, it is trying to add the following directory to the code path: `AppDir: "/Users/motiejus/code/tchannel-erlang/_build/coveralls/lib/tchannel"`, which doesn't exist.

Failed travis-ci run (look at the bottom for `make coveralls`): https://travis-ci.org/Motiejus/tchannel-erlang/jobs/120550013

Patch to coveralls to reveal the added directory:

```diff
motiejus ~/code/tchannel-erlang/_checkouts/coveralls $ git diff
diff --git a/src/rebar3_coveralls.erl b/src/rebar3_coveralls.erl
index fecffb0..c813ebf 100644
--- a/src/rebar3_coveralls.erl
+++ b/src/rebar3_coveralls.erl
@@ -86,6 +86,7 @@ format_error(Reason) ->
 cover_paths(State) ->
   lists:foreach(fun(App) ->
                     AppDir = rebar_app_info:out_dir(App),
+                    io:format(user, "AppDir: ~p~n", [AppDir]),
                     true   = code:add_path(filename:join([AppDir, "ebin"])),
                     true   = code:add_path(filename:join([AppDir, "test"]))
                 end,
```

Stack trace (you can also see it in travis-ci):
```
===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace
===> Uncaught error: {badmatch,{error,bad_directory}}
===> Stack trace to the error location: [{rebar3_coveralls,
                                                 '-cover_paths/1-fun-0-',1,
                                                 [{file,
                                                   "/Users/motiejus/code/tchannel-erlang/_checkouts/coveralls/src/rebar3_coveralls.erl"},
                                                  {line,90}]},
                                                {lists,foreach,2,
                                                 [{file,"lists.erl"},
                                                  {line,1337}]},
                                                {rebar3_coveralls,
                                                 cover_paths,1,
                                                 [{file,
                                                   "/Users/motiejus/code/tchannel-erlang/_checkouts/coveralls/src/rebar3_coveralls.erl"},
                                                  {line,87}]},
                                                {rebar3_coveralls,do,1,
                                                 [{file,
                                                   "/Users/motiejus/code/tchannel-erlang/_checkouts/coveralls/src/rebar3_coveralls.erl"},
                                                  {line,68}]},
                                                {rebar_core,do,2,
                                                 [{file,
                                                   "/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
                                                  {line,125}]},
                                                {rebar_prv_do,do_tasks,2,
                                                 [{file,
                                                   "/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_prv_do.erl"},
                                                  {line,68}]},
                                                {rebar_core,do,2,
                                                 [{file,
                                                   "/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
                                                  {line,125}]},
                                                {rebar_prv_do,do_tasks,2,
                                                 [{file,
                                                   "/home/travis/build/rebar/rebar3/_build/default/lib/rebar/src/rebar_prv_do.erl"},
                                                  {line,68}]}]
```

Thank you for looking into this!

**Comment by Motiejus** [comment]
For completeness, latest `dev` (as of writing, https://github.com/Motiejus/tchannel-erlang/tree/6911591dc1f1920ef388ba41121d643fb99bc3ac) is using `test` profile for coveralls, and that works: https://travis-ci.org/Motiejus/tchannel-erlang/jobs/120552470

**Comment by Motiejus** [comment]
I recognize that my project setup is non-trivial (the requirements could be smaller). If you want, I can spend some time changing my project so you don't need python/virtualenv to reproduce the original issue. Just let me know.

**Comment by markusn** [comment]
I'm not very familiar with rebar3 but probably the test directory doesn't exist when not using the test profile. Should probably add a filelib:is_dir before trying to add the path.

**Comment by markusn** [comment]
Try the rebar3-test-folder-fix . It should work (ignores the result for the test folder as it may not exist)

**Comment by Motiejus** [comment]
I made this change to use coveralls in it's own profile: https://github.com/Motiejus/tchannel-erlang/commit/b8cd57b8ccc7e47569a24b9816e9951c16050b97

Unfortunately, it still fails: https://travis-ci.org/Motiejus/tchannel-erlang/jobs/121411827

**Comment by surik** [comment]
Why do you run tests and coverlalls in different profiles? If I remember it correct coveralls needs beam files because calls module_info for them.

**Comment by Motiejus** [comment]
Ah, I never thought it requires the beam files. Oops.

I am running coveralls in it's own profile, so that coveralls plugin isn't fetched/compiled each time I run the tests locally. If having the beam files a hard requirement, I have two ways out:

1. Execute unit tests in travis in a different profile other than test.
2. In non-travis case, do not expose coveralls plugin in test profile (which is what I currently do).

@markusn can you confirm reading the beam files is required? In that case the issue is invalid and I will close it.

Thank you for following up on this.

**Comment by markusn** [comment]
Yes, it will need the beam-files to do module_info. I thought the problem was that there isn't  always a test directory.

**Comment by Motiejus** [comment]
I see. I don't think it would be a good idea to read beam files from the other profile, so let's call it a day. Thank you!
