### ISSUE TITLE
any idea how to make this work with circle ci?

### ISSUE THREAD

**Issue by aeyakovenko** [markusn/coveralls-erl#18]
any idea how to make this work with circle ci?

**Comment by markusn** [comment]
Have you tried setting {coveralls_service_name, "circleci"} in rebar.config and then in rebar.config.script setting coveralls_service_job_id to os:getenv("CIRCLE_BUILD_NUM") ?

**Comment by markusn** [comment]
Usage with CircleCI implemented and described in the README by @evanmcc
