### ISSUE TITLE
rebar3 as test coveralls send

### ISSUE THREAD

**Issue by facundoolano** [markusn/coveralls-erl#23]
Hi, I'm trying this plugin, and I've found that `rebar3 coveralls send` fails in my project. I had to run `rebar3 as test coveralls send` for it to pick up the coverdata file. This does look like the most frequent case, I can send a PR updating the README if it makes sense.

**Comment by markusn** [comment]
Hi, that sounds weird. Do you have a project and commit that I could have a look at? (As well as the rebar3 version used).

**Comment by facundoolano** [comment]
Sure this is the commit where I added the covearalls-erl code: https://github.com/lambdaclass/throttle/commit/7e9d9b2462edd8d49864a960e6afd4edcef7ccbb

You can see that the Makefile does:

```
./rebar3 ct --name node1@127.0.0.1 ; ./rebar3 as test coveralls send
```

If your remove the `as test` it will fail as mentioned.

The rebar3 binary is included in the repository: rebar 3.4.1 on Erlang/OTP 20 Erts 9.1.5

Also, here's a travis build that failed, with rebar debug enabled: https://travis-ci.org/lambdaclass/throttle/builds/313719265

**Comment by markusn** [comment]
Is there any reason to only specify  {coveralls_coverdata    , "_build/test/cover/ct.coverdata"} and {coveralls_service_name , "travis-ci"} in the test profile? It probably works as expected (no as test) if those are moved outside the test profile.

**Comment by facundoolano** [comment]
I put it there since those are test only configurations, but I did try using the default profile before and it failed the same.

I put together a branch with the coveralls config in the default profile and removing the `as test` from the `coveralls send`. You can see the failing build here (with rebar3 debug on):

https://travis-ci.org/lambdaclass/throttle/builds/314757226

**Comment by markusn** [comment]
Seems like the new problem is that there is a dep that is only used in the test profile that makes coveralls crash when trying to import the cover data. In either case it is probably a good idea to document this, I will update the README, thanks for the issue. Btw the simplest way to solve your problem is probably to run rebar3 do ct --name node1@127.0.0.1, coveralls send. At least with my version of rebar3 it makes coveralls run using the test profile (and makes a nice oneliner).

**Comment by facundoolano** [comment]
I think I'll stick with the `rebar3 as test coveralls send`, I like it better. Thanks for reviewing!
