### ISSUE TITLE
source_digest not part of the source file object

### ISSUE THREAD

**Issue by shamis** [markusn/coveralls-erl#27]
As per coveralls api source_digest is required
```json
{
  "service_job_id": "1234567890",
  "service_name": "travis-ci",
  "source_files": [
    {
      "name": "example.rb",
      "source_digest": "asdfasdf1234asfasdf2345",
      "coverage": [null, 1, null]
    },
    {
      "name": "lib/two.rb",
      "source_digest": "asdf1234asdfsdfggsfgd9423",
      "coverage": [null, 1, 0, null]
    }
  ]
}
```
but it seems like `source_digest` is not send with the json_file 
https://github.com/markusn/coveralls-erl/blob/749eb6352afb8a3041933467f435131713bae856/src/coveralls.erl#L198-L203

**Comment by markusn** [comment]
This must be a fairly recent addition. I'm happy to take a PR fixing this issue.
