### ISSUE TITLE
Is it compatible with Github Action?

### ISSUE THREAD

**Issue by HJianBo** [markusn/coveralls-erl#31]
Hi, @markusn Thanks for providing so convenient for coveralls. But I've only seen examples related to travis-ci. Does it work in GitHub Action?

**Comment by markusn** [comment]
@HJianBo it should probably work but I've not tried it. Set the service name to `github` and the job id to the commit hash

**Comment by robertoaloi** [comment]
@HJianBo @markusn Tried the rebar3 / GitHub Actions / Coveralls setup with Erlang LS (https://github.com/erlang-ls/erlang_ls). Created a PR with the instructions coming from that experience.

**Comment by markusn** [comment]
Thanks! @robertoaloi

**Comment by HJianBo** [comment]
Thanks guys, This guide is very useful to me :)
