### ISSUE TITLE
Task for sending data

### ISSUE THREAD

**Issue by surik** [markusn/coveralls-erl#6]
Plugin sends covedata after eunit or ct tasks but sometimes I want to merge coverdatas before send

It would look like `rebar skip_deps=true eunit ct send-coveralls`

What do you think about?

**Comment by markusn** [comment]
Hi!

The idea sounds good ass long as the current behaviour stays the same when not using the new functionality!

Thanks for your contributions to the project!

**Comment by surik** [comment]
Backward compatibility is good but in this case if we added `send-coveralls` we don't start coveralls task after `eunit` and `ct`.

Maybe we could add option which turn off old behavior?
