### ISSUE TITLE
Using meck

### ISSUE THREAD

**Issue by surik** [markusn/coveralls-erl#9]
Now coveralls-erl is supporting meck.
Maybe we could use this instead of self-made mocking tool?

**Comment by markusn** [comment]
Hi! coveralls-erl will not use meck. It shoud have no dependencies apart from the Erlang standard library. Besides there is no point in using meck when the code is written in such a way that it is possible to test it without meck (which is the case for coveralls-erl).

**Comment by surik** [comment]
Ok, I see your point. But when the code of this plugin will be much more(I'm going to add some features) It will be difficult to test with self-made mocking tool.

Could we return to this issue after sometime?

**Comment by markusn** [comment]
In my experience using a mocking in tool is almost never needed if taking testing in consideration when making the design. Of course it could be that this will not be the case, I will close this until there is an  need to discuss it again.
